/**
 * Data provenance — every verifiable value in the plot catalog carries one
 * of these so the UI can render a clickable badge with a frozen-in-time
 * source artefact (Geoportal screenshot, uploaded PDF, ULDK API response).
 *
 * Schema source: ADR-0002 §2.4 (`docs/adr/0002-3d-viewer-and-data-layer.md`).
 *
 * Trust ladder:
 *   high   — geoportal-wms / uldk         (state register, frozen screenshot)
 *   medium — manual-upload                (signed PDF from gmina or seller)
 *   low    — declared                     (seller's word, no document)
 *   none   — fallback-typical             (our default for "MN suburban Krakow")
 */

export type DataProvenanceSource =
  | "geoportal-wms"
  | "uldk"
  | "manual-upload"
  | "declared"
  | "fallback-typical";

export type DataProvenanceTrust = "high" | "medium" | "low" | "none";

export interface DataProvenance {
  /** Where the value originated. Determines badge colour and modal contents. */
  source: DataProvenanceSource;
  /** Cached trust tier for cheap UI lookup. Must match the implicit tier of `source`. */
  trust: DataProvenanceTrust;
  /** ISO timestamp of the last fetch / upload. Renders next to the badge. */
  fetchedAt: string;
  /**
   * For `geoportal-wms`: R2 path or absolute URL of the frozen screenshot
   * (`provenance/{slug}/{layer}-{fetchedAt}.png`). Generated by the
   * `generate-provenance-screenshots` worker (F1-T7).
   */
  screenshotUrl?: string;
  /**
   * For `manual-upload`: R2 path or absolute URL of the original document
   * (PDF wypis z MPZP, decyzja WZ, etc.).
   */
  documentUrl?: string;
  /** Human-readable filename for the document badge. */
  documentName?: string;
}

/**
 * Map of field name → its provenance. Sits on the parent container so we
 * don't have to wrap every primitive in `{ value, provenance }`.
 *
 * Example:
 *   const planning: PlanningConditions = {
 *     landUse: "Zabudowa MN",
 *     ...
 *     provenance: {
 *       landUse: { source: "manual-upload", trust: "medium", ... },
 *       maxHeight: { source: "fallback-typical", trust: "none", ... },
 *     },
 *   };
 *
 * F1-T9 ships an ESLint rule that requires every verifiable field to have
 * a corresponding key in this map at build time.
 */
export type ProvenanceFields<T> = Exclude<keyof T, "provenance">;
export type ProvenanceMap<T> = Partial<Record<ProvenanceFields<T> & string, DataProvenance>>;

/** Helper: trust → badge style token (consumed by `<ProvenanceBadge>` in F3-T4). */
export const PROVENANCE_BADGE_STYLE: Record<DataProvenanceTrust, string> = {
  high: "moss",
  medium: "clay",
  low: "amber",
  none: "amber-warning",
};
